Models/CallbackModel.cs
using System;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ProcessMonitor.Models
{
    public class CallbackModel
    {
        [JsonPropertyName("id")]
        public Guid Id { get; set; }
        [JsonPropertyName("url")]
        public string Url { get; set; }
        public async Task Call(MessageModel message)
        {
            var request = (HttpWebRequest)WebRequest.Create(this.Url);
            var data = Encoding.ASCII.GetBytes(JsonSerializer.Serialize(message));
            request.Method = "POST";
            request.ContentType = "application/json";
            request.ContentLength = data.Length;
            using (var stream = request.GetRequestStream())
            {
                await stream.WriteAsync(data, 0, data.Length);
            }
            var response = (HttpWebResponse)await request.GetResponseAsync();
        }
    }
}

Models/ErrorViewModel.cs
namespace ProcessMonitor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FullModel.cs
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ProcessMonitor.Models
{
    public class FullModel
    {
        [JsonPropertyName("processes")]
        public IList<ProcessModel> Processes { get; set; }
        [JsonPropertyName("state")]
        public StateModel State { get; set; }
    }
}

Models/MessageModel.cs
using System.Text;
using System.Text.Json.Serialization;

namespace ProcessMonitor.Models
{
    public class MessageModel
    {
        [JsonPropertyName("message")]
        public string Message { get; set; }
        public MessageModel() { }
        public MessageModel(StateModel state, double ramTreshold, double cpuTreshold)
        {
            var builder = new StringBuilder();
            if (state.RAMusage > ramTreshold) builder.Append($"ALARM! Current RAM usage is {state.RAMusage}%, when RAM treshold is {ramTreshold}%!");
            if (state.CPUusage > cpuTreshold) builder.Append($"{(builder.Length > 0 ? "\n" : "")}ALARM! Current CPU usage is {state.CPUusage}%, when CPU treshold is {cpuTreshold}%!");
            this.Message = builder.ToString();
        }
    }
}

Models/ProcessModel.cs
using System.Diagnostics;
using System.Text.Json.Serialization;

namespace ProcessMonitor.Models
{
    public class ProcessModel
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }
        [JsonPropertyName("working-set-64")]
        public long WorkingSet64 { get; set; }
        [JsonPropertyName("private-memory-size-64")]
        public long PrivateMemorySize64 { get; set; }
        [JsonPropertyName("name")]
        public string Name { get; set; }
        public ProcessModel() { }
        public ProcessModel(Process process)
        {
            Id = process.Id;
            Name = process.ProcessName;
            WorkingSet64 = process.WorkingSet64;
            PrivateMemorySize64 = process.PrivateMemorySize64;
        }
    }
}

Models/StateModel.cs
using System.Text.Json.Serialization;

namespace ProcessMonitor.Models
{
    public class StateModel
    {
        [JsonPropertyName("cpu-usage")]
        public double CPUusage { get; set; }
        [JsonPropertyName("ram-usage")]
        public double RAMusage { get; set; }
    }
}

Controllers/CallbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ProcessMonitor.Configurations;
using ProcessMonitor.Core;
using ProcessMonitor.Models;

namespace ProcessMonitor.Controllers
{
    public class CallbacksController : Controller
    {
        private readonly ILogger<CallbacksController> _logger;
        private readonly IMonitorService _monitorService;
        private readonly ICallbacksStorageService _callbackStorageService;
        private readonly AppSettings _appSettings;
        public CallbacksController(IOptions<AppSettings> settings, IMonitorService monitorService, ICallbacksStorageService callbackStorageService, ILogger<CallbacksController> logger)
        {
            _logger = logger;
            _monitorService = monitorService;
            _appSettings = settings.Value;
            _callbackStorageService = callbackStorageService;
            _monitorService.CallbackCall += CallbackCalls;
        }
        private async Task CallbackCalls(MessageModel message)
        {
            try
            {
                var callbacks = await _callbackStorageService.GetCallbacksAsync();
                var tasks = new List<Task>();
                callbacks.ToList().ForEach(callback => tasks.Add(callback.Call(message)));
                await Task.WhenAll(tasks);
            }
            catch (Exception ex)
            {
                _logger.LogError(1, ex, "We should send message, but any exception throwed!");
            }
        }
        [HttpGet("callbacks")]
        public async Task<IList<CallbackModel>> ViewCallbacks() => await _callbackStorageService.GetCallbacksAsync();
        [HttpGet("callbacks/{id}")]
        public async Task<CallbackModel> ViewCallback(Guid id) => await _callbackStorageService.GetCallbackAsync(id);
        [HttpPost("callbacks/register")]
        public async Task RegisterCallback([FromBody]CallbackModel callback) => await _callbackStorageService.RegisterCallbackAsync(callback);
        [HttpGet("callbacks/{id}/delete")]
        public async Task DeleteCallback(Guid id) => await _callbackStorageService.RemoveCallbackAsync(id);
    }
}

Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ProcessMonitor.Configurations;
using ProcessMonitor.Core;
using ProcessMonitor.Models;

namespace ProcessMonitor.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

Controllers/ProcessesController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ProcessMonitor.Configurations;
using ProcessMonitor.Core;
using ProcessMonitor.Models;

namespace ProcessMonitor.Controllers
{
    public class ProcessesController : Controller
    {
        private readonly ILogger<ProcessesController> _logger;
        private readonly IMonitorService _monitorService;
        private readonly AppSettings _appSettings;
        private static MessageModel _lastMessage;
        public ProcessesController(IOptions<AppSettings> settings, IMonitorService monitorService, ILogger<ProcessesController> logger)
        {
            _logger = logger;
            _monitorService = monitorService;
            _appSettings = settings.Value;
            _monitorService.CallbackCall += CallbackCallHandler;
        }
        public IActionResult Index() => View(BuildFullModel());
        [HttpGet("processes/api")]
        public IActionResult ApiIndex() => Json(BuildFullModel());
        [HttpGet("processes/api/polling")]
        public async Task<IActionResult> DoLongPolling()
        {
            var message = await WaitAlarm();
            if (message == null) return new ObjectResult(new { Status = "Long polling timeout!" });
            else return new ObjectResult(new { Status = "OK", Data = message });
        }
        private Task CallbackCallHandler(MessageModel message) => Task.Run(() => _lastMessage = message);
        private async Task<MessageModel> WaitAlarm()
        {
            _lastMessage = null;
            var start = DateTime.UtcNow;
            while ((DateTime.UtcNow - start).TotalMilliseconds < _appSettings.PollingTimeout)
            {
                if (_lastMessage != null) return _lastMessage;
                await Task.Delay(100);
            }
            if (_lastMessage != null) return _lastMessage;
            return null;
        }
        private FullModel BuildFullModel() => new FullModel() { State = _monitorService.GetState(), Processes = _monitorService.GetProcesses() };
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Process Monitor Welcome Page";
}

<div >
   
<h1 id="process-monitor">Process monitor</h1>
<p>There is web tool for monitoring VM processes.</p>
<h2 id="web-pages">Web pages</h2>
<p>There are only two web pages
<a href="http://localhost:5000/">http://localhost:5000/</a> and <a href="http://localhost:5000/processes">http://localhost:5000/processes</a></p>
<p>On the <strong>Home page</strong> we can see instruction and description. On the <strong>Processes page</strong>  we can see current system state and all runned processed.</p>
<p>We will see notifiction, when CPU or RAM will greater than configured tresholds.</p>
<h2 id="api-endpoints">API endpoints</h2>
<p>This web app provide follow api endpoints:</p>
<p><a href="http://localhost:5000/processes/api">http://localhost:5000/processes/api</a>         - returns state and processes information</p>
<p><a href="http://localhost:5000/processes/api/polling">http://localhost:5000/processes/api/polling</a> - implement long polling mechanism for get notifications</p>
<p><a href="http://localhost:5000/callbacks/">http://localhost:5000/callbacks/</a>            - returns all registered callbacks</p>
<p><a href="http://localhost:5000/callbacks/id">http://localhost:5000/callbacks/id</a>          - returns registered callback by id</p>
<p><a href="http://localhost:5000/callbacks/register">http://localhost:5000/callbacks/register</a>    - register new callback</p>
<p><a href="http://localhost:5000/callbacks/%7Bid%7D/delete">http://localhost:5000/callbacks/{id}/delete</a> - delete registered callbacks by id</p>
<h3 id="callbacks-mechanism">Callbacks mechanism</h3>
<p>Client can register callback endpoint (http url), and app will send notifications to this endpoint via Http  (GET).</p>
<p>In current version all registered callback saved in json file.</p>
<h2 id="architecture">Architecture</h2>
<p>There is classic ASP.NET Core MVC web application.</p>
<pre class="hljs"><code><div>├── appsettings.json    //application configuration
├── Configurations      //configuration models
│   ├── AppSettings.cs  
│   ├── CallbacksStorageConfiguration.cs
│   └── MonitorConfiguration.cs
├── Controllers         //MVC controllers
│   ├── CallbacksController.cs  //Callbacks mechanism
│   ├── HomeController.cs       //Home page
│   └── ProcessesController.cs  //Processes (main) controller
├── core
│   ├── CallbacksStorageService.cs  // Simple implementation for ICallbacksStorageService. All callbacks will saved in file in json format
│   ├── ICallbacksStorageService.cs // Interface for CallbackStorages. Provide method for store callback endpoints.
│   ├── IMonitorService.cs  //Default IMonitorService implementation
│   ├── MonitorService.cs   //Interface for MonitorServices. Provide methods for get current VM state and processes. Call &quot;CallbackCall&quot; event, when any alarm happend
│   └── ShellHelper.cs      //Class for call system shell
├── Models
│   ├── CallbackModel.cs
│   ├── ErrorViewModel.cs
│   ├── FullModel.cs
│   ├── MessageModel.cs
│   ├── ProcessModel.cs
│   └── StateModel.cs
├── process_monitor.csproj
├── Program.cs
├── Properties
│   └── launchSettings.json
├── README.md
├── Startup.cs
├── Views
│   ├── Home
│   │   └── Index.cshtml
│   ├── Processes
│   │   └── Index.cshtml
│   ├── Shared
│   │   ├── Error.cshtml
│   │   ├── _Layout.cshtml
│   │   └── _ValidationScriptsPartial.cshtml
│   ├── _ViewImports.cshtml
│   └── _ViewStart.cshtml
└── wwwroot
    ├── css
    │   ├── processes.css   //Processes page styles
    │   └── site.css
    ├── favicon.ico
    └── js
        ├── processes.js    //Processes page script
        └── site.js

</div></code></pre>
<h2 id="what-could-do-in-future">What could do in future</h2>
<ul>
<li>save registered callbacks to db (e.g. Sqlite or Mongo). It could realized if develop new implementation for ICallbacksStorageService.</li>
<li>use Vue.js or React for FrontEnd instead of jQuery (for more extendable logic)</li>
<li>beautify pages for more pretty view</li>
<li>implement access control</li>
<li>use websockets instead of longPolling</li>
<li>extend ProcessModel for provide mor information about processes</li>
<li>extend StateModel for provide more information about VM state</li>
<li>implement sort in processes table (e.g. by id, name, CPU or RAM usage)</li>
</ul>

</div>

@section Styles {
    <link href="@Url.Content("~/css/home.css")" rel="stylesheet" type="text/css" />
}

Views/Processes/Index.cshtml
@model ProcessMonitor.Models.FullModel

@{
    ViewData["Title"] = "ProcessesMonitor";
}


<div class="processes-page">
    <div class="state-panel">
        <h1 class="display-4">State</h1>
        <div class="pair">
            <div class="left">CPU usage: </div>
            <div class="right" id="cpu">@(Model.State.CPUusage) %</div>
        </div> 
        <div class="pair">
            <div class="left">RAM usage: </div>
            <div class="right" id="ram">@(Model.State.RAMusage) %</div>
        </div> 
    </div>
    <div class="processes-panel">
        <h1 class="display-4">Processes</h1>
        <table id="processes-table">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>PrivateMemorySize64</th>
                <th>WorkingSet64</th>
            </tr>
            @foreach (var item in Model.Processes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrivateMemorySize64)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WorkingSet64)
                    </td>
                </tr>
            }
        </table>
    </div>    
</div>


@section Styles {
    <link href="@Url.Content("~/css/processes.css")" rel="stylesheet" type="text/css" />
}
@section Scripts {
    <script src="~/js/processes.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Process Monitor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
     @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">process_monitor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Processes" asp-action="Index">Processes</a>
                        </li>
                    </ul>
                </div>
                <div class="notification">jhgfylkjhjhgjk</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Process Monitor
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>